ENV_NAME: card-game
ROLLOUT_LENGTH: 128
ENV_KWARGS:
  max_steps: 8
  obs_type: image
  shuffle: true
  fixed_partner_pos: -1
  other_play_position_shuffle: false
  other_play_recolouring: false
  comm_reward_coef: 0.0
TASK_NAME: card-game
