ENV_NAME: card-game
ROLLOUT_LENGTH: 128
ENV_KWARGS:
  max_steps: 8
  obs_type: image
  shuffle: true
  other_play_position_shuffle: true
  other_play_recolouring: true
  focal_card_idx: 0
  focal_card_reward: 0.9
  default_match_reward: 1.0
  match_coef: 0.0
  follow_coef: 0.0
TASK_NAME: card-game-op-paper
