ENV_NAME: card-game
ROLLOUT_LENGTH: 128
ENV_KWARGS:
  max_steps: 2
  obs_type: image
  shuffle: true
  other_play_position_shuffle: false
  other_play_recolouring: true
  unique_card_task: true
  unique_card_color_idx: 0
  comm_reward_coef: 0.0
  comm_stability_bonus: 0.0
  comm_follow_bonus: 0.0
TASK_NAME: card-game-op-unique-card
