defaults:
  - ja_ippo/_base_
  - _self_

TOTAL_TIMESTEPS: 5e6
NUM_ENVS: 64
NUM_SEEDS: 5
ENT_COEF: 0.01
FEED_OTHER_ATTN: false
COMMUNICATION: false
COMM_WARMUP_ENV_STEPS: 0
COMM_REWARD_START_SCALE: 0.5
