ENV_NAME: overcooked-v2
ROLLOUT_LENGTH: 256
ENV_KWARGS:
  layout: demo_cook_simple
  obs_type: image
  agent_view_size: 2
  max_steps: 400
  negative_rewards: true
  random_agent_positions: true
  sample_recipe_on_delivery: true
  do_reward_shaping: false
  egocentric: true
  agent_fov_size: 5
  agent_fov_centered: true
  rotate_obs: false
  op_ingredient_permutations:
  - 0
  - 1
TASK_NAME: overcooked-v2/demo_cook_simple-op-ego
